#############################################################################
# Makefile for building: MT
# Generated by qmake (2.01a) (Qt 4.6.2) on: ?? 6? 25 15:39:07 2014
# Project:  MT.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile MT.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		config.cpp \
		tools.cpp \
		opt/cJSON.c \
		git.cpp \
		pushcode.cpp \
		vo/bug.cpp \
		test.cpp \
		opt/xmlhelper.cpp moc_mainwindow.cpp \
		moc_config.cpp \
		moc_tools.cpp \
		moc_git.cpp \
		moc_pushcode.cpp \
		moc_test.cpp \
		qrc_res.cpp
OBJECTS       = main.o \
		mainwindow.o \
		config.o \
		tools.o \
		cJSON.o \
		git.o \
		pushcode.o \
		bug.o \
		test.o \
		xmlhelper.o \
		moc_mainwindow.o \
		moc_config.o \
		moc_tools.o \
		moc_git.o \
		moc_pushcode.o \
		moc_test.o \
		qrc_res.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		MT.pro
QMAKE_TARGET  = MT
DESTDIR       = 
TARGET        = MT

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_config.h ui_tools.h ui_git.h ui_pushcode.h ui_test.h ui_buginfo.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MT.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile MT.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile MT.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/MT1.0.0 || $(MKDIR) .tmp/MT1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MT1.0.0/ && $(COPY_FILE) --parents mainwindow.h config.h tools.h opt/cJSON.h git.h pushcode.h vo/bug.h test.h opt/xmlhelper.h .tmp/MT1.0.0/ && $(COPY_FILE) --parents res.qrc .tmp/MT1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp config.cpp tools.cpp opt/cJSON.c git.cpp pushcode.cpp vo/bug.cpp test.cpp opt/xmlhelper.cpp .tmp/MT1.0.0/ && $(COPY_FILE) --parents mainwindow.ui config.ui tools.ui git.ui pushcode.ui test.ui ../MT2/buginfo.ui .tmp/MT1.0.0/ && (cd `dirname .tmp/MT1.0.0` && $(TAR) MT1.0.0.tar MT1.0.0 && $(COMPRESS) MT1.0.0.tar) && $(MOVE) `dirname .tmp/MT1.0.0`/MT1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MT1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_config.cpp moc_tools.cpp moc_git.cpp moc_pushcode.cpp moc_test.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_config.cpp moc_tools.cpp moc_git.cpp moc_pushcode.cpp moc_test.cpp
moc_mainwindow.cpp: config.h \
		tools.h \
		git.h \
		test.h \
		vo/bug.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_config.cpp: config.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) config.h -o moc_config.cpp

moc_tools.cpp: tools.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tools.h -o moc_tools.cpp

moc_git.cpp: git.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) git.h -o moc_git.cpp

moc_pushcode.cpp: git.h \
		pushcode.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) pushcode.h -o moc_pushcode.cpp

moc_test.cpp: vo/bug.h \
		test.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) test.h -o moc_test.cpp

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		view-refresh.svg \
		search.svg
	/usr/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_config.h ui_tools.h ui_git.h ui_pushcode.h ui_test.h ui_buginfo.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_config.h ui_tools.h ui_git.h ui_pushcode.h ui_test.h ui_buginfo.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_config.h: config.ui
	/usr/bin/uic-qt4 config.ui -o ui_config.h

ui_tools.h: tools.ui
	/usr/bin/uic-qt4 tools.ui -o ui_tools.h

ui_git.h: git.ui
	/usr/bin/uic-qt4 git.ui -o ui_git.h

ui_pushcode.h: pushcode.ui
	/usr/bin/uic-qt4 pushcode.ui -o ui_pushcode.h

ui_test.h: test.ui
	/usr/bin/uic-qt4 test.ui -o ui_test.h

ui_buginfo.h: ../MT2/buginfo.ui
	/usr/bin/uic-qt4 ../MT2/buginfo.ui -o ui_buginfo.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		config.h \
		tools.h \
		git.h \
		test.h \
		vo/bug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		config.h \
		tools.h \
		git.h \
		test.h \
		vo/bug.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

config.o: config.cpp config.h \
		ui_config.h \
		opt/cJSON.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config.o config.cpp

tools.o: tools.cpp tools.h \
		ui_tools.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tools.o tools.cpp

cJSON.o: opt/cJSON.c opt/cJSON.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o cJSON.o opt/cJSON.c

git.o: git.cpp git.h \
		ui_git.h \
		config.h \
		pushcode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o git.o git.cpp

pushcode.o: pushcode.cpp pushcode.h \
		git.h \
		ui_pushcode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pushcode.o pushcode.cpp

bug.o: vo/bug.cpp vo/bug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bug.o vo/bug.cpp

test.o: test.cpp test.h \
		vo/bug.h \
		ui_test.h \
		config.h \
		opt/xmlhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test.o test.cpp

xmlhelper.o: opt/xmlhelper.cpp opt/xmlhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmlhelper.o opt/xmlhelper.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_config.o: moc_config.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_config.o moc_config.cpp

moc_tools.o: moc_tools.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tools.o moc_tools.cpp

moc_git.o: moc_git.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_git.o moc_git.cpp

moc_pushcode.o: moc_pushcode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pushcode.o moc_pushcode.cpp

moc_test.o: moc_test.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_test.o moc_test.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

